### ISSUE TITLE
Faulty link in the column moving topic

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-docfx#1196]
Steps to reproduce:
1. Open https://www.infragistics.com/angularsite/components/grids_templates/column_moving.html
2. Scroll to the "Additional Resources" section.
3. Click on @@igComponent overview

Actual result:
The page is 404-ing

Expected results:
The link should take you to the correct page.

**Comment by zdrawku** [comment]
@valadzhov this is not something that should be fixed. All links related to the grid templates are accessible only if you type in them manually.

**Comment by HristoP96** [comment]
@valadzhov  The link you have provide is takes to the grids_templates. These are templates, which are used for generating grid topics based on the Grid type. For example @@igComponent will be replaced with IgxGridComponent or IgxTreeGridComponent or IgxHierarchicalGridComponent.
This issue is not to fix, since the links work fine in the topics generated from this template, which are:
 - [https://www.infragistics.com/angularsite/components/hierarchicalgrid/column_moving.html](https://www.infragistics.com/angularsite/components/hierarchicalgrid/column_moving.html)
 
- [https://www.infragistics.com/angularsite/components/treegrid/column_moving.html](https://www.infragistics.com/angularsite/components/treegrid/column_moving.html) 

- [https://www.infragistics.com/angularsite/components/grid/column_moving.html](https://www.infragistics.com/angularsite/components/grid/column_moving.html)
