### ISSUE TITLE
Warning and Note headers are in English

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-docfx#127]
1. Go here:
https://jp.staging.infragistics.local/angularsite/components/list.html
2. Observe the warning and note.

Actual result:
The headers "WARNING" and "NOTE" are in English.  I did not translate `[!WARNING]` and `[!NOTE]` assuming they were indicators of CSS styles.  If this is not true and all I need to do is translate that, please let me know. 

Expected result:
The headers should be localized in CSS?

**Comment by zdrawku** [comment]
Hey Liz, Warning and Note are two of the four types of [note blocks](https://docs.microsoft.com/en-us/contribute/help-crr/help-content/contribute/contribute-how-to-write-use-markdown) to draw attention to specific content. They should be localized, yes.

Keep in mind that docfx does not provide API for this and Simeon discovered a way to overcome this by using a resources-en.json configuration.

I can add values for all note blocks in order to localize them, although this will happen next week.
