### ISSUE TITLE
Improve Combo Value Binding paragraph

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-docfx#1480]
Update Combo Value Binding [paragraph](https://www.infragistics.com/products/ignite-ui-angular/angular/components/combo_features.html#value-binding), using the new combo [improvement](https://github.com/IgniteUI/igniteui-angular/issues/5217).

**Comment by dafo** [comment]
We should point out that when we use the combo with a remote data, in case we want to bind to the combo's `[(ngModel)]`, we should set the selected items inside the callback of the `getData` method of the remote service. Something like:
```
this.remoteService.getData(initSize,
  null, (data) => {
  this.remoteCombo.totalItemCount = data["@odata.count"];
  this.selectedItems = [1, 3];
});
```
Otherwise the checkboxes for the selected items would be checked but the values would not be displayed in the combo.
