### ISSUE TITLE
Right Menu does not contains all items

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-docfx#2151]
In the IgniteUI Angular documentation when you open a certain topic the right navigation menu does not contain all items.
Result:
![image](https://user-images.githubusercontent.com/34240583/89649648-cb5b3600-d8c9-11ea-940c-eb4b0e956034.png)
Expected Result:
![image](https://user-images.githubusercontent.com/34240583/89649699-da41e880-d8c9-11ea-9d3d-7b0fcf285564.png)

**Comment by HristoP96** [comment]
This issue is not reproducible on production environment, only on staging. The reason for this behavior is caused by a SEO cookie, named **_mkto_trk**. The cookie is used from [Marketo’s Munchkin Tracker](https://docs.marketo.com/display/public/DOCS/Add+Munchkin+Tracking+Code+to+Your+Website), which for some reason optimizes the affix list items with a className - **mchNoDecorate** and prevents the necessary classes to be applied, in order the top level sections to expand their children. 

The things, that needs investigation, regarding this behavior are:

- How is this cookie added  only to some certain users
- How could it be entirely removed from the browser
- Why this cookie modifies the page, in a way that breaks it.
- Why do we have a SEO cookie on private staging environment and on production everything is fine

Along these questions others may occur, but we cannot let this be unsolved
