### ISSUE TITLE
Add 'Code View' View for the demos in the topics

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx#2367]
Create a POC that introduces two menu buttons:

Example - that will present the current iframe
Code view - that will lead to multiple choices of code files (component.ts, HTML, and styles)

Note: This should be discussed with the Design team

**Comment by tosharky** [comment]
This is the design prototype, discussed with Stefan.

https://cloud.indigo.design/share/run/66y294mu7e10#f=example

Be advised, look at it at 90% zoom in the browser. Don't know why it opens it a bit larger.

**Comment by tosharky** [comment]
I made a little change. Added a COPY button when on a tab with code that can be copied. This is for ease of use and it's been discussed with Stefan.

Also, can I ask, since I saw the demo on the Sprint Review, to make the hover on the tabs without the white background. Only the text to change in blue. Sorry, this is something that I didn't communicate earlier.
