### ISSUE TITLE
Responsive igx-grid columns

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-docfx#25]
Add a demo and code example of how to make the grid columns responsive, meaning to hide some of them on small screens and show them on larger screens.

**Comment by simeonoff** [comment]
@SlavUI We don't have this functionality in the grid yet.

**Comment by kdinev** [comment]
@simeonoff It doesn't make sense to make this a feature of the grid, as it is easily achievable on an application level. Documentation is all that is needed.

**Comment by simeonoff** [comment]
@kdinev in that case I am including @zdrawku as he is the one who built the grid sample.

**Comment by zdrawku** [comment]
We are going to add a demo and code snippet to the upcomming Grid Hiding topic. 
Meanwhile here is a code snippet showing how to implement hiding of a column (have a look at windowWidth and ngAfterViewInit())

**component.html**
```
<igx-column field="AthleteNumber" header="Athlete number" [hidden]="windowWidth < 785">
        <ng-template igxHeader>
            <span class="cellAlignSyle">Athlete number</span>
        </ng-template>
</igx-column>
```

**component.ts**

```
public windowWidth: any;

...

public ngAfterViewInit() {
      this.grid1.paginationTemplate = this.pager;
      this.grid1.perPage = 6;
      this.windowWidth = (window.innerWidth);
 }
```

[Grid demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html) (resize the screen to less than 785px in order to hide AthleteNumber column
