### ISSUE TITLE
Update above the fold content on Angular data grid page

### ISSUE THREAD

**Issue by aatanasov2** [IgniteUI/igniteui-docfx#3010]
We want to add a generic paragraph and image to the Angular Data grid page  

https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid
 

![image](https://user-images.githubusercontent.com/72744305/140725536-a49b874f-b596-40f7-a8c5-296a526e107e.png)

The goal is to target featured snippet for the primary keyword "angular data grid" currently triggered by Syncfusion

![image](https://user-images.githubusercontent.com/72744305/140727443-20a1033f-ca6e-4fcf-b520-f0adfbcf74e2.png)

**Comment by aatanasov2** [comment]
@hanastasov In the document, we've made recommendations for an additional paragraph and image

https://infragisticsinc297.sharepoint.com/:w:/r/Groups/marketing/_layouts/15/Doc.aspx?sourcedoc=%7B85d760f9-0dfd-4901-8280-3b2abb69756c%7D

Let me know your opinion

**Comment by hanastasov** [comment]
Can we choose another image of a grid? It may be from the same grid, but with proper alignment. The one on the doc file has some misaligmnets in the toolbar (I guess it was because of window size, when taking the screenshot).

Maybe this one:
![image](https://user-images.githubusercontent.com/14248932/141760715-c95a639f-4896-4713-b690-29f87f35380c.png)

**Comment by zdrawku** [comment]
I spoke with Aleks and we've decided to change the image with:
![landing-grid-page](https://user-images.githubusercontent.com/11193764/143230963-e61eea63-f2a1-4547-847c-78c341a1847d.PNG)
