### ISSUE TITLE
Broken API links of Charts, Maps and Excel Library in Angular documentation

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-docfx#3677]
The API links of all charts, maps and Excel library components are not working
![image](https://github.com/IgniteUI/igniteui-docfx/assets/52423497/968d750c-bf49-4f7b-b89c-e1cce51bc1bf)

For example:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/charts/types/bar-chart
https://www.infragistics.com/products/ignite-ui-angular/angular/components/geo-map-type-scatter-area-series
https://www.infragistics.com/products/ignite-ui-angular/angular/components/excel-library-using-cells

**Comment by zdrawku** [comment]
The team is aware of the problem and currently working on a more sustainable solution to fix it. Adding @HUSSAR-mtrela as well

**Comment by gmurray81** [comment]
did someone rollback the api site or something, @zdrawku ? This seems ok in prod atm. Something is definitely up on staging though, it seems like the base path for the api links isn't getting injected appropriately. Maybe something was altered with this.

**Comment by gmurray81** [comment]
BTW, I fixed the paths for the staging environment, just been working on try to get new API docs sites deployed. Unfortunately, this has proved tricky due to all the infrastructure changes we are making with the source control. I'm trying to manually update WC on staging to see if everything aligns

CC: @HUSSAR-mtrela  ^^

**Comment by zdrawku** [comment]
It is working well no on both staging and production, thanks Graham
