### ISSUE TITLE
better description on grid - performance page

### ISSUE THREAD

**Issue by kmatev** [IgniteUI/igniteui-docfx#393]
Hi team,

Please add a description to the performance sample here:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_virtualization.html 

In the description, please clarify how many rows/columns the grid is bound to by default, and give detailed instructions how the user can open the stackblitz view and where exactly to modify the number of records/columns bound to the grid.

This will allow users to easily test performance in the scenarios they need.

Kiril

**Comment by mpavlinov** [comment]
@kmatev "how the user can open the stackblitz view" not sure I understand what you mean here. I guess you're not talking about instructing the user how to click on the purple button "View on Stackblitz". Can you clarify?

**Comment by MayaKirova** [comment]
@kmatev Assuming that the documentation targets developers I’m not sure we need to go into that much details since the code can be easily viewed and edited in Stackblitz.
Anyone having basic Angular knowledge should be able to understand the code  fairly easily and edit it to test the amount of data he/she wants to display.

Perhaps what you really need is a more marketing oriented sample where the rows/columns count can be changed via the UI, so that people not familira with Angular can use it to test different configurations. Perhaps something similar to the IgniteUI's performance sample, where you can change the count of the rows/columns via a slider:
https://www.igniteui.com/grid/grid-performance

If that’s the case perhaps we can discuss adding another sample specifically for that purpose. Let me know what you think.

**Comment by kmatev** [comment]
Hi Maia,

Thanks for this.

You’re right, we need a separate sample where users can choose the amount of rows and columns of data bound to the control.

Is it a lot of work to add a brief description to the existing sample to improve it until we deliver this separate sample?

Can we prioritise that?

Best,
Kiril

**Comment by MayaKirova** [comment]
@kmatev Could you give an example on what a good description would look like to you?

Currently I’m not sure I understand the points you’ve listed, specifically: 
1. give detailed instructions how the user can open the stackblitz view
Do you mean instruction on how to click the "View on Stackblitz" button?

2. where exactly to modify the number of records/columns bound to the grid.
Do you mean which line of code the user needs to change?

If you could clarify what you expect to see that would be great.

**Comment by kmatev** [comment]
Hi Maya,

Let me clarify what I meant earlier:

(1)   I meant that ideally, that there should be a message saying “In order to modify the number of records bound to this grid, please click the VIEW ON STACKBLITZ button below and modify the code in <file name>, and update the value on <line number> to the desired number of records.” Is there a way we can extract the number of records as a setting that can be modified more easily without going into the file itself?

(2)   Can we increase the height of the grid by about 30% to make sure more records are shown, and to add the following message above the sample – “Efficient use of virtualization allows the igxGrid to achieve a high level of performance when showing large datasets. The grid below is bound to 10,000 records.”

Please let me know if you’d like to discuss this with anyone else – there could be better wording, but I think we need to add these clarifications to make the sample more useful.

Best,
Kiril

**Comment by MayaKirova** [comment]
@kmatev Thank you for the clarification.

For (1) – So basically you want instructions on how to edit the sample for non-technical people, right?
I don’t think the docs are the place for such information since they target developers, who should be able to read and edit basic angular code. I don’t think non-technical people would benefit much from reading the docs anyway since it uses technical terms and code examples that would not make sense to an average end-user.

We could make the rows/columns count settable via some UI element (sliders, inputs or something else) however I don’t think this particular sample is the ideal candidate for this since its idea is to show commodity trading prices, so the columns and data that we can show are limited. Perhaps we can discuss with the UX department what kind of data and concept would look good with large number of columns/rows  so that it would show some real-world use case (perhaps something financial with a lot of numeric columns and lots and lots of records).

For (2) – Sure. We can add a section above the demo with this information in the docs. I don’t mind making the sample bigger either.

**Comment by mpavlinov** [comment]
@kmatev I agree with Maya that such description is not appropriate for the current help topics.
