### ISSUE TITLE
Hammer.js warning on List View

### ISSUE THREAD

**Issue by jVanZwieten** [IgniteUI/igniteui-docfx#67]
https://www.infragistics.com/products/ignite-ui-angular/angular/components/list.html

The warning about Hammer.js below the demo is non-sequitur. It doesn't pertain directly to this control, and is therefore confusing to have here. If we want this warning, we should have it on the 'getting started with IgniteUI for Angular' page: https://www.infragistics.com/products/ignite-ui-angular/getting-started

**Comment by zdrawku** [comment]
Hey John, sorry for the late response. Actually it is important to mention the Hammer JS dependency especially for the list component, because of all gesture interactions. As for the Getting started page, we did mention the Hammer JS dependency:

> To install Ignite UI for Angular in your project, run:
$ npm install igniteui-angular Hammerjs @types/hammerjs --save 
// Note: Hammerjs and @types/hammerjs are dependencies required by the Ignite UI for Angular
